title: Cybersecurity Learning Progress Blog
tagline: Documenting my journey into cybersecurity
description: My personal cybersecurity learning blog, portfolio, notes and progress tracker.

url: "https://USERNAME.github.io"
baseurl: "/REPO"

github:
  username: StanGar30
