title: Cybersecurity Learning Progress Blog
tagline: Documenting my journey into cybersecurity
description: My personal cybersecurity learning blog, portfolio, notes and progress tracker.

url: "https://StanGar30.github.io"
baseurl: "/cybersecurity_learning_blog"

github:
  username: StanGar30
